openapi: 3.0.3
info:
  title: STAC API - Complete
  version: 1.0.0-beta.1
apis:
  - url: 'build/core/openapi.yaml'
  - url: 'build/item-search/openapi.yaml'
    dereference:
      circular: ignore
  - url: 'build/ogcapi-features/openapi.yaml'
    paths:
      exclude:
        - /
    dereference:
      circular: ignore
  - url: 'build/ogcapi-features/extensions/transaction/openapi.yaml'
    dereference:
      circular: ignore
  - url: 'build/ogcapi-features/extensions/version/openapi.yaml'
    dereference:
      circular: ignore
